import Head from 'next/head'
import Example from '@/Components/Functional/example'



export default function Home({time}: any) {


  const revalidate =()  => {
    fetch('/api/revalidate')
  }
  return (
    <>
      <Head>
        <title>Project</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>{time}</h1>
      <button onClick={() => revalidate()}>Revalidate Time</button>
      <Example/>
     
    </>
  )
}


export function getStaticProps() {

  console.log('Getting Static Props') 

  return {
    props: {
      time: new Date().getTime()
    },
    revalidate: 100

  }
}